logging:
  level:
    org.springframework: info

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      show-sql: true
  datasource:
    url: jdbc:mysql://openmind-db.csc9suvgmtxj.ap-northeast-2.rds.amazonaws.com:3306/openmind
    username: admin
    password: openmind
  main:
    allow-bean-definition-overriding: true





